name: Run Newman Postman Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: |
          newman run Admin.postman_collection.json \
            -e Admin.postman_environment.json \
            --reporters cli,html,junit \
            --reporter-html-export newman-report.html \
            --reporter-junit-export newman-results.xml

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: |
            newman-report.html
            newman-results.xml
